version: "3.5"
networks:
  default:
    name: pesto

services:
  auth:
    container_name: pesto_auth
    image: pesto-challenge/auth
    # command: sh -c "while true; do echo hello; sleep 2; done"
    volumes:
      - /tmp/config.yaml:/home/app/config.yaml
    environment:
      - AUTH_CONFIG_YAML=/home/app
    ports:
      - 3000:3000
    depends_on:
      - postgres-db

  postgres-db:
    container_name: pesto_postgres_db
    image: postgres:15
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2G
    #     reservations:
    #       memory: 1G
    ports:
      - 5432:5432
    # volumes:
      # - ../db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
      # - 
    environment:
      - POSTGRES_USER=pesto
      - POSTGRES_PASSWORD=pest02024
      - POSTGRES_DB=pesto
    command:
      - "postgres"
      - "-N"
      - "500"
    